name: util
version: 0.1.0.0
synopsis: Collection of utility functions
description: See README at <https://github.com/gallery/haskell/math#readme>
maintainer: Jeremy Dobbins-Bucklad <j.american.db@gmail.com>
github: jad-b/gallery
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - directory
  - filepath

library:
  source-dirs: src
  exposed-modules:
    - FileSys
